// GENERATO da `pnpm assets manifest`: non modificare a mano.
// Gli asset grafici pronti per il gioco (tools/assets, GUIDA Blocco C §4). Percorsi relativi alla pagina.
export interface ArtAsset { src: string; src2x: string; png: string; thumb?: string; w: number; h: number }

export const ASSETS = {
  'illustrazioni/awayCurse': { src: 'art/illustrazioni/awayCurse.webp', src2x: 'art/illustrazioni/awayCurse@2x.webp', png: 'art/illustrazioni/awayCurse.png', thumb: 'art/illustrazioni/awayCurse-256.webp', w: 512, h: 512 },
  'illustrazioni/boardUnrest': { src: 'art/illustrazioni/boardUnrest.webp', src2x: 'art/illustrazioni/boardUnrest@2x.webp', png: 'art/illustrazioni/boardUnrest.png', thumb: 'art/illustrazioni/boardUnrest-256.webp', w: 512, h: 512 },
  'illustrazioni/cleanRun': { src: 'art/illustrazioni/cleanRun.webp', src2x: 'art/illustrazioni/cleanRun@2x.webp', png: 'art/illustrazioni/cleanRun.png', thumb: 'art/illustrazioni/cleanRun-256.webp', w: 512, h: 512 },
  'illustrazioni/comeback': { src: 'art/illustrazioni/comeback.webp', src2x: 'art/illustrazioni/comeback@2x.webp', png: 'art/illustrazioni/comeback.png', thumb: 'art/illustrazioni/comeback-256.webp', w: 512, h: 512 },
  'illustrazioni/comebackKid': { src: 'art/illustrazioni/comebackKid.webp', src2x: 'art/illustrazioni/comebackKid@2x.webp', png: 'art/illustrazioni/comebackKid.png', thumb: 'art/illustrazioni/comebackKid-256.webp', w: 512, h: 512 },
  'illustrazioni/crisis': { src: 'art/illustrazioni/crisis.webp', src2x: 'art/illustrazioni/crisis@2x.webp', png: 'art/illustrazioni/crisis.png', thumb: 'art/illustrazioni/crisis-256.webp', w: 512, h: 512 },
  'illustrazioni/debut': { src: 'art/illustrazioni/debut.webp', src2x: 'art/illustrazioni/debut@2x.webp', png: 'art/illustrazioni/debut.png', thumb: 'art/illustrazioni/debut-256.webp', w: 512, h: 512 },
  'illustrazioni/drought': { src: 'art/illustrazioni/drought.webp', src2x: 'art/illustrazioni/drought@2x.webp', png: 'art/illustrazioni/drought.png', thumb: 'art/illustrazioni/drought-256.webp', w: 512, h: 512 },
  'illustrazioni/fans': { src: 'art/illustrazioni/fans.webp', src2x: 'art/illustrazioni/fans@2x.webp', png: 'art/illustrazioni/fans.png', thumb: 'art/illustrazioni/fans-256.webp', w: 512, h: 512 },
  'illustrazioni/feud': { src: 'art/illustrazioni/feud.webp', src2x: 'art/illustrazioni/feud@2x.webp', png: 'art/illustrazioni/feud.png', thumb: 'art/illustrazioni/feud-256.webp', w: 512, h: 512 },
  'illustrazioni/ffp': { src: 'art/illustrazioni/ffp.webp', src2x: 'art/illustrazioni/ffp@2x.webp', png: 'art/illustrazioni/ffp.png', thumb: 'art/illustrazioni/ffp-256.webp', w: 512, h: 512 },
  'illustrazioni/flop': { src: 'art/illustrazioni/flop.webp', src2x: 'art/illustrazioni/flop@2x.webp', png: 'art/illustrazioni/flop.png', thumb: 'art/illustrazioni/flop-256.webp', w: 512, h: 512 },
  'illustrazioni/formerClub': { src: 'art/illustrazioni/formerClub.webp', src2x: 'art/illustrazioni/formerClub@2x.webp', png: 'art/illustrazioni/formerClub.png', thumb: 'art/illustrazioni/formerClub-256.webp', w: 512, h: 512 },
  'illustrazioni/fortress': { src: 'art/illustrazioni/fortress.webp', src2x: 'art/illustrazioni/fortress@2x.webp', png: 'art/illustrazioni/fortress.png', thumb: 'art/illustrazioni/fortress-256.webp', w: 512, h: 512 },
  'illustrazioni/giant': { src: 'art/illustrazioni/giant.webp', src2x: 'art/illustrazioni/giant@2x.webp', png: 'art/illustrazioni/giant.png', thumb: 'art/illustrazioni/giant-256.webp', w: 512, h: 512 },
  'illustrazioni/hatTrick': { src: 'art/illustrazioni/hatTrick.webp', src2x: 'art/illustrazioni/hatTrick@2x.webp', png: 'art/illustrazioni/hatTrick.png', thumb: 'art/illustrazioni/hatTrick-256.webp', w: 512, h: 512 },
  'illustrazioni/hotStreak': { src: 'art/illustrazioni/hotStreak.webp', src2x: 'art/illustrazioni/hotStreak@2x.webp', png: 'art/illustrazioni/hotStreak.png', thumb: 'art/illustrazioni/hotStreak-256.webp', w: 512, h: 512 },
  'illustrazioni/hothead': { src: 'art/illustrazioni/hothead.webp', src2x: 'art/illustrazioni/hothead@2x.webp', png: 'art/illustrazioni/hothead.png', thumb: 'art/illustrazioni/hothead-256.webp', w: 512, h: 512 },
  'illustrazioni/keeper': { src: 'art/illustrazioni/keeper.webp', src2x: 'art/illustrazioni/keeper@2x.webp', png: 'art/illustrazioni/keeper.png', thumb: 'art/illustrazioni/keeper-256.webp', w: 512, h: 512 },
  'illustrazioni/lateWinner': { src: 'art/illustrazioni/lateWinner.webp', src2x: 'art/illustrazioni/lateWinner@2x.webp', png: 'art/illustrazioni/lateWinner.png', thumb: 'art/illustrazioni/lateWinner-256.webp', w: 512, h: 512 },
  'illustrazioni/leaky': { src: 'art/illustrazioni/leaky.webp', src2x: 'art/illustrazioni/leaky@2x.webp', png: 'art/illustrazioni/leaky.png', thumb: 'art/illustrazioni/leaky-256.webp', w: 512, h: 512 },
  'illustrazioni/mentor': { src: 'art/illustrazioni/mentor.webp', src2x: 'art/illustrazioni/mentor@2x.webp', png: 'art/illustrazioni/mentor.png', thumb: 'art/illustrazioni/mentor-256.webp', w: 512, h: 512 },
  'illustrazioni/nemesis': { src: 'art/illustrazioni/nemesis.webp', src2x: 'art/illustrazioni/nemesis@2x.webp', png: 'art/illustrazioni/nemesis.png', thumb: 'art/illustrazioni/nemesis-256.webp', w: 512, h: 512 },
  'illustrazioni/newSigning': { src: 'art/illustrazioni/newSigning.webp', src2x: 'art/illustrazioni/newSigning@2x.webp', png: 'art/illustrazioni/newSigning.png', thumb: 'art/illustrazioni/newSigning-256.webp', w: 512, h: 512 },
  'illustrazioni/preSigned': { src: 'art/illustrazioni/preSigned.webp', src2x: 'art/illustrazioni/preSigned@2x.webp', png: 'art/illustrazioni/preSigned.png', thumb: 'art/illustrazioni/preSigned-256.webp', w: 512, h: 512 },
  'illustrazioni/predestined': { src: 'art/illustrazioni/predestined.webp', src2x: 'art/illustrazioni/predestined@2x.webp', png: 'art/illustrazioni/predestined.png', thumb: 'art/illustrazioni/predestined-256.webp', w: 512, h: 512 },
  'illustrazioni/redemption': { src: 'art/illustrazioni/redemption.webp', src2x: 'art/illustrazioni/redemption@2x.webp', png: 'art/illustrazioni/redemption.png', thumb: 'art/illustrazioni/redemption-256.webp', w: 512, h: 512 },
  'illustrazioni/relegation': { src: 'art/illustrazioni/relegation.webp', src2x: 'art/illustrazioni/relegation@2x.webp', png: 'art/illustrazioni/relegation.png', thumb: 'art/illustrazioni/relegation-256.webp', w: 512, h: 512 },
  'illustrazioni/revenge': { src: 'art/illustrazioni/revenge.webp', src2x: 'art/illustrazioni/revenge@2x.webp', png: 'art/illustrazioni/revenge.png', thumb: 'art/illustrazioni/revenge-256.webp', w: 512, h: 512 },
  'illustrazioni/scorerRace': { src: 'art/illustrazioni/scorerRace.webp', src2x: 'art/illustrazioni/scorerRace@2x.webp', png: 'art/illustrazioni/scorerRace.png', thumb: 'art/illustrazioni/scorerRace-256.webp', w: 512, h: 512 },
  'illustrazioni/showdown': { src: 'art/illustrazioni/showdown.webp', src2x: 'art/illustrazioni/showdown@2x.webp', png: 'art/illustrazioni/showdown.png', thumb: 'art/illustrazioni/showdown-256.webp', w: 512, h: 512 },
  'illustrazioni/slump': { src: 'art/illustrazioni/slump.webp', src2x: 'art/illustrazioni/slump@2x.webp', png: 'art/illustrazioni/slump.png', thumb: 'art/illustrazioni/slump-256.webp', w: 512, h: 512 },
  'illustrazioni/surprise': { src: 'art/illustrazioni/surprise.webp', src2x: 'art/illustrazioni/surprise@2x.webp', png: 'art/illustrazioni/surprise.png', thumb: 'art/illustrazioni/surprise-256.webp', w: 512, h: 512 },
  'illustrazioni/talisman': { src: 'art/illustrazioni/talisman.webp', src2x: 'art/illustrazioni/talisman@2x.webp', png: 'art/illustrazioni/talisman.png', thumb: 'art/illustrazioni/talisman-256.webp', w: 512, h: 512 },
  'illustrazioni/thrashing': { src: 'art/illustrazioni/thrashing.webp', src2x: 'art/illustrazioni/thrashing@2x.webp', png: 'art/illustrazioni/thrashing.png', thumb: 'art/illustrazioni/thrashing-256.webp', w: 512, h: 512 },
  'illustrazioni/titleRace': { src: 'art/illustrazioni/titleRace.webp', src2x: 'art/illustrazioni/titleRace@2x.webp', png: 'art/illustrazioni/titleRace.png', thumb: 'art/illustrazioni/titleRace-256.webp', w: 512, h: 512 },
  'illustrazioni/unbeaten': { src: 'art/illustrazioni/unbeaten.webp', src2x: 'art/illustrazioni/unbeaten@2x.webp', png: 'art/illustrazioni/unbeaten.png', thumb: 'art/illustrazioni/unbeaten-256.webp', w: 512, h: 512 },
  'illustrazioni/veteran': { src: 'art/illustrazioni/veteran.webp', src2x: 'art/illustrazioni/veteran@2x.webp', png: 'art/illustrazioni/veteran.png', thumb: 'art/illustrazioni/veteran-256.webp', w: 512, h: 512 },
  'illustrazioni/wantsOut': { src: 'art/illustrazioni/wantsOut.webp', src2x: 'art/illustrazioni/wantsOut@2x.webp', png: 'art/illustrazioni/wantsOut.png', thumb: 'art/illustrazioni/wantsOut-256.webp', w: 512, h: 512 },
  'illustrazioni/winStreak': { src: 'art/illustrazioni/winStreak.webp', src2x: 'art/illustrazioni/winStreak@2x.webp', png: 'art/illustrazioni/winStreak.png', thumb: 'art/illustrazioni/winStreak-256.webp', w: 512, h: 512 },
  'sfondi/board': { src: 'art/sfondi/board.webp', src2x: 'art/sfondi/board@2x.webp', png: 'art/sfondi/board.png', w: 1280, h: 720 },
  'sfondi/desk': { src: 'art/sfondi/desk.webp', src2x: 'art/sfondi/desk@2x.webp', png: 'art/sfondi/desk.png', w: 1280, h: 720 },
  'sfondi/dressing': { src: 'art/sfondi/dressing.webp', src2x: 'art/sfondi/dressing@2x.webp', png: 'art/sfondi/dressing.png', w: 1280, h: 720 },
  'sfondi/finance': { src: 'art/sfondi/finance.webp', src2x: 'art/sfondi/finance@2x.webp', png: 'art/sfondi/finance.png', w: 1280, h: 720 },
  'sfondi/fixtures': { src: 'art/sfondi/fixtures.webp', src2x: 'art/sfondi/fixtures@2x.webp', png: 'art/sfondi/fixtures.png', w: 1280, h: 720 },
  'sfondi/market': { src: 'art/sfondi/market.webp', src2x: 'art/sfondi/market@2x.webp', png: 'art/sfondi/market.png', w: 1280, h: 720 },
  'sfondi/scouts': { src: 'art/sfondi/scouts.webp', src2x: 'art/sfondi/scouts@2x.webp', png: 'art/sfondi/scouts.png', w: 1280, h: 720 },
  'sfondi/squad': { src: 'art/sfondi/squad.webp', src2x: 'art/sfondi/squad@2x.webp', png: 'art/sfondi/squad.png', w: 1280, h: 720 },
  'sfondi/stories': { src: 'art/sfondi/stories.webp', src2x: 'art/sfondi/stories@2x.webp', png: 'art/sfondi/stories.png', w: 1280, h: 720 },
  'sfondi/tactics': { src: 'art/sfondi/tactics.webp', src2x: 'art/sfondi/tactics@2x.webp', png: 'art/sfondi/tactics.png', w: 1280, h: 720 },
  'sfondi/training': { src: 'art/sfondi/training.webp', src2x: 'art/sfondi/training@2x.webp', png: 'art/sfondi/training.png', w: 1280, h: 720 },
  'sfondi/youth': { src: 'art/sfondi/youth.webp', src2x: 'art/sfondi/youth@2x.webp', png: 'art/sfondi/youth.png', w: 1280, h: 720 },
  'texture/carta': { src: 'art/texture/carta.webp', src2x: 'art/texture/carta@2x.webp', png: 'art/texture/carta.png', w: 512, h: 512 },
  'texture/erba': { src: 'art/texture/erba.webp', src2x: 'art/texture/erba@2x.webp', png: 'art/texture/erba.png', w: 512, h: 512 },
} as const satisfies Record<string, ArtAsset>;

export type AssetName = keyof typeof ASSETS;

/** per i nomi composti a runtime (lo sfondo di una schermata): se manca, si resta senza immagine */
export const art = (name: string): ArtAsset | undefined => (ASSETS as Record<string, ArtAsset>)[name];
