blank_issues_enabled: true
contact_links:
  - name: Idee e racconti delle vostre stagioni
    url: https://github.com/XmarcoS10/talisman/discussions
    about: Per proposte e impressioni, meglio le Discussioni.
